# Generated by Django 5.0.3 on 2024-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_historicalproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripcion de Productos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripcion de Productos'),
        ),
    ]
